### ISSUE TITLE
ci to build scala artifact with tests on pr and merge and release

### ISSUE THREAD

**Issue by antonovdmitriy** [antonovdmitriy/crud-wishlist-scala-sqlite#2]

**Comment by antonovdmitriy** [comment]
[ ]  enable scovarage plugin


```scala
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.9.2")
```


```scala
enablePlugins(ScoveragePlugin)
```

```scala
// Set minimum coverage percentage threshold to 80%
coverageMinimum := 80

// Exclude certain files or packages from coverage analysis
coverageExcludedPackages := "com.example.myapp.api.*" :: Nil
coverageExcludedFiles := "com/example/myapp/Main.scala" :: Nil

// Configure report generation options
coverageReportHTML := true
coverageReportCobertura := true

```

```yml
      - name: Run tests with Scoverage
        run: sbt clean coverage test

      - name: Generate Scoverage reports
        run: sbt coverageReport
```
